# Generated by Django 5.1.7 on 2025-06-17 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kimdan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Uchun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Valyuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('short', models.CharField(max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('summa', models.DecimalField(decimal_places=2, max_digits=12)),
                ('summa_type', models.CharField(choices=[('naqd', 'Naqd'), ('plastik', 'Plastik'), ('bank', 'Bank')], default='naqd', max_length=20)),
                ('izoh', models.TextField(blank=True, null=True)),
                ('kimdan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.kimdan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('valuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.valyuta')),
            ],
        ),
        migrations.CreateModel(
            name='Chiqim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('summa', models.DecimalField(decimal_places=2, max_digits=12)),
                ('summa_type', models.CharField(choices=[('naqd', 'Naqd'), ('plastik', 'Plastik'), ('bank', 'Bank')], default='naqd', max_length=20)),
                ('izoh', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('uchun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.uchun')),
                ('valuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.valyuta')),
            ],
        ),
    ]
