# Generated by Django 5.1.7 on 2025-06-17 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(blank=True, default='profil_rasmlari/default.png', null=True, upload_to='profil_rasmlari/')),
                ('manzil', models.CharField(blank=True, max_length=255, null=True)),
                ('tugilgan_sana', models.DateField(blank=True, null=True)),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('tasdiqla_kod', models.CharField(blank=True, max_length=6, null=True)),
                ('kod_vaqt', models.DateTimeField(auto_now=True)),
                ('is_login', models.BooleanField(default=False)),
                ('is_profile_completed', models.BooleanField(default=False)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.valyuta')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
