# Generated by Django 5.2.3 on 2025-06-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='rasm',
            field=models.ImageField(blank=True, default='profile/default.png', null=True, upload_to='profil_rasmlari/'),
        ),
    ]
