# Generated by Django 5.2.3 on 2025-06-21 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_alter_profil_rasm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='is_profile_completed',
        ),
        migrations.AlterField(
            model_name='profil',
            name='rasm',
            field=models.ImageField(blank=True, default='media/default.png', null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='tasdiqla_kod',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
